name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
env:
  KUBECONFIG: ${{ github.workspace }}/.kube/pod-kubeconfig
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and publish images
        timeout-minutes: 15
        run: |
          docker buildx build --push -t mogior/rsoi_cars_service:v1 -f src/cars_service/Dockerfile src/cars_service
          docker buildx build --push -t mogior/rsoi_gate_way_service:v1 -f src/gate_way_service/Dockerfile src/gate_way_service
          docker buildx build --push -t mogior/rsoi_rental_service:v1 -f src/rental_service/Dockerfile src/rental_service
          docker buildx build --push -t mogior/rsoi_payment_service:v1 -f src/payment_service/Dockerfile src/payment_service

      - name: Deploy
        run: |
          mkdir -p '${{ github.workspace }}/.kube' \
                    && echo '${{ secrets.KUBECONFIG}}' | base64 -d > $KUBECONFIG
          helm upgrade app --kubeconfig $KUBECONFIG .k8s/charts/services
          sleep 60

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v3/postman/collection.json
          environment: v3/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"